# Database Configuration for H2
spring.r2dbc.url=r2dbc:h2:mem:///testdb
spring.r2dbc.username=sa
spring.r2dbc.password=

# SQL Initialization
spring.sql.init.mode=always
spring.sql.init.platform=h2
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.encoding=UTF-8

# Logging for database initialization and R2DBC
logging.level.root=INFO
logging.level.org.springframework.r2dbc=DEBUG
logging.level.org.springframework.r2dbc.core=DEBUG
logging.level.org.springframework.boot.sql.init=DEBUG
logging.level.org.springframework.data.r2dbc=DEBUG
logging.level.com.packt.ahmeric.reactivesample=DEBUG

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
