name: Chapter-5-1
services:
  db:
    image: postgres:18.3-alpine3.22
    environment:
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: bookstore
    ports:
      - '127.0.0.1:5432:5432'
    restart: always

  mongodb:
    image: mongodb/mongodb-community-server:8.2-ubi8-slim
    environment:
      MONGO_INITDB_DATABASE: bookstore
    ports:
      - '127.0.0.1:27017:27017'
    restart: always
